Remove platform key
This is to resolve the following issue while using sign_target_files_apks.

Rewriting VENDOR/etc/selinux/vendor_mac_permissions.xml with new keys.
Traceback (most recent call last):
AssertionError: Found duplicate entries after cert replacement: <?xml version="1.0" encoding="iso-8859-1"?><!-- AUTOGENERATED FILE DO NOT MODIFY --><policy><signer signature ……

This is because the platform key is alrady defined here. No need to add it again.
system/sepolicy/vendor/keys.conf
system/sepolicy/vendor/mac_permissions.xml

Change-Id: I8b0566579849f9e953bc783fc1f5eb0a9ec977d9