sepolicy: fix cts err because of permissions.
java.lang.NullPointerException: Attempt to
invoke virtual method 'int android.graphics.Bitmap.getXxx()'
on a null object reference

Change-Id: Iffa6ee536db740baf24bce3da0107f787a72938f
Signed-off-by: Bian Jin chen <kenjc.bian@rock-chips.com>