common: fix some app preinstall compile failed
error: mismatch in the <uses-library> tags between the build system and the manifest:
        - required libraries in build system: []
                         vs. in the manifest: []
        - optional libraries in build system: []
                         vs. in the manifest: [org.apache.http.legacy]
        - tags in the manifest (xxxxx):
                uses-library-not-required:'org.apache.http.legacy'

Signed-off-by: wh <wanghang@rock-chips.com>
Change-Id: I6a81ec01ec8e6284cdf24ab6b7f687e9ff228a0f