Add missing config file for apex.
Error: /apex/com.android.runtime/bin/linkerconfig failed:
    No such file or directory.

Test: Boot into android shell

Signed-off-by: Bian Jin chen <kenjc.bian@rock-chips.com>
Change-Id: I8997862c8a5f786a0fb4ad98790fa5c354bb97f7